In [1]:
import torch
import numpy as np
import gzip
import pickle
import torch.nn.functional as F
import math
import torchvision
import torchvision.transforms as transforms

from torch.utils.data import DataLoader
from sklearn.metrics import roc_curve, auc

import src.Model
import src.Utils
import src.Log

from tqdm import tqdm

with gzip.open('train_dataset.pkl.gz', 'rb') as f:
    train_set = pickle.load(f)

In [3]:
train_set
from torch.utils.data import Subset

# Lấy 200 mẫu đầu tiên từ train_ds để làm D0
D0 = Subset(train_set, range(200))


In [6]:
D0

[(tensor([98.0000, 91.0000, 49.0000, 63.0000, 21.0000, 36.7222, 95.0000]),
  tensor([  2.8000,   4.0000,  -1.0000,   2.4000,  23.0000,  -1.0000, 105.0000,
            0.4000,  84.0000,   9.9000,  28.5000, 203.0000,   3.3000,  -1.0000,
          137.0000,   5.5000]),
  tensor(0.)),
 (tensor([ 95.0000, 110.0000,  65.0000,  75.0000,  16.0000,  37.6667,  95.0000]),
  tensor([  3.2000,   5.0000,   0.4000,   1.3000,  22.0000,   4.0000, 109.0000,
            0.7000,  82.0000,  12.0000,  35.6000, 238.0000,   3.8000,  31.6000,
          142.0000,  13.3000]),
  tensor(0.)),
 (tensor([ 59.0000, 125.0000,  45.0000,  71.6667,  19.0000,  36.2778,  91.0000]),
  tensor([  4.0000,  31.0000,   0.4000,  -1.0000,  35.0000,  -1.0000, 105.0000,
            1.5000, 136.0000,  12.9000,  37.3000, 193.0000,   4.2000,  26.6000,
          146.0000,   4.9000]),
  tensor(0.)),
 (tensor([ 70.0000, 131.0000,  74.0000,  95.0000,  14.0000,  37.3333, 100.0000]),
  tensor([ -1.0000,  79.0000,  -1.0000,   1.1000,  17.0000

In [8]:
import torch 
torch.save(D0, 'D0_dataset.pt')

In [10]:
train_ds = torch.load('D0_dataset.pt')
D0

[(tensor([98.0000, 91.0000, 49.0000, 63.0000, 21.0000, 36.7222, 95.0000]),
  tensor([  2.8000,   4.0000,  -1.0000,   2.4000,  23.0000,  -1.0000, 105.0000,
            0.4000,  84.0000,   9.9000,  28.5000, 203.0000,   3.3000,  -1.0000,
          137.0000,   5.5000]),
  tensor(0.)),
 (tensor([ 95.0000, 110.0000,  65.0000,  75.0000,  16.0000,  37.6667,  95.0000]),
  tensor([  3.2000,   5.0000,   0.4000,   1.3000,  22.0000,   4.0000, 109.0000,
            0.7000,  82.0000,  12.0000,  35.6000, 238.0000,   3.8000,  31.6000,
          142.0000,  13.3000]),
  tensor(0.)),
 (tensor([ 59.0000, 125.0000,  45.0000,  71.6667,  19.0000,  36.2778,  91.0000]),
  tensor([  4.0000,  31.0000,   0.4000,  -1.0000,  35.0000,  -1.0000, 105.0000,
            1.5000, 136.0000,  12.9000,  37.3000, 193.0000,   4.2000,  26.6000,
          146.0000,   4.9000]),
  tensor(0.)),
 (tensor([ 70.0000, 131.0000,  74.0000,  95.0000,  14.0000,  37.3333, 100.0000]),
  tensor([ -1.0000,  79.0000,  -1.0000,   1.1000,  17.0000